### ISSUE TITLE
大陆碧蓝航线手游上线有大量立绘

### ISSUE THREAD

**Issue by MadRanger** [harukaxxxx/WOWS-TechTreeMoe#6]
_(:з」∠)_望知悉 我来没来得及打包资源

**Comment by MadRanger** [comment]
对了还有p站的Scharnhorst
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=36560930

**Comment by harukaxxxx** [comment]
碧藍航線由熱心的小夥伴提供打包圖已經有許多艦船更新上了
（應該就是貼吧1.3那包）
然而就在剛剛我已經掌握碧藍航線的拆包技術
往後艦B更新時我也能自行處理了！

**Comment by MadRanger** [comment]
https://pan.baidu.com/s/1bpjHuiz

**Comment by harukaxxxx** [comment]
抱歉前陣子比較忙
已經把你做的沙恩放上去了唷！！
