### ISSUE TITLE
戰艦少女2017夏活新船

### ISSUE THREAD

**Issue by jason199506** [harukaxxxx/WOWS-TechTreeMoe#7]
巴哈留言你好像沒看所以跑來這裡戳

能跟WOWS對應上的一共4條：紐倫堡/z46/h39/明斯克

紐倫堡：
https://zh.moegirl.org/zh-hant/%E6%88%98%E8%88%B0%E5%B0%91%E5%A5%B3:%E7%BA%BD%E4%BC%A6%E5%A0%A1

Z46：
https://zh.moegirl.org/zh-hant/%E6%88%98%E8%88%B0%E5%B0%91%E5%A5%B3:Z46

H39興登堡(T9德戰腓特烈大帝)：
https://zh.moegirl.org/zh-hant/%E6%88%98%E8%88%B0%E5%B0%91%E5%A5%B3:%E7%BA%BD%E4%BC%A6%E5%A0%A1

明斯克：
https://zh.moegirl.org/zh-hant/%E6%88%98%E8%88%B0%E5%B0%91%E5%A5%B3:%E6%98%8E%E6%96%AF%E5%85%8B

哦內該～

**Comment by harukaxxxx** [comment]
已經加入Trello囉！
感謝你！
https://trello.com/b/jDWgIB9p

**Comment by jason199506** [comment]
趁這issue還沒close順便爆個bug
碧藍航線的約克是皇家窯子船HMS York，不是德國的Yorck

![image](https://user-images.githubusercontent.com/16889734/29500472-e93193da-85ee-11e7-9435-8cdbc1d6cf98.png)
你把碧藍的約克丟到德國那邊去了

**Comment by jason199506** [comment]
持續報bug

1)碧藍航線的企業(USS CV6 enterprise T8金幣航母) 你丟到T6銀幣獨立去了

2)T8金幣戰列 阿拉巴馬，艦R有出該級首艦南達科他
原版：http://i.imgur.com/vUNuvPL.jpg
換裝“歸鄉的少女”：http://i.imgur.com/LEwDxYG.png

3)戰艦少女 密蘇里新出了兩個換裝
輕鬆一夏：http://i.imgur.com/m3YYBgB.png
私人定制：http://i.imgur.com/ud6GYkr.png

4)T3美巡st louis........
科技樹上的是USS C-20 St Louis (1905)
你說把重名的布魯克林級聖路易斯(USS CL-49 St Louis)放著也說得過去，海倫娜布魯克林......╮(╯▽╰)╭跟st louis完全扯不上關係啊
(史實美國科技樹：奧馬哈級->布魯克林級(含艦R聖路易斯)->亞特蘭大級+克里夫蘭級)

5)T8美國銀幣驅逐benson，艦R出了benson級的船(DD-459拉菲)：http://i.imgur.com/3nPoUrg.png

6)日本T89銀幣航母，艦R雙鶴大鳳都開改了
翔鶴：http://i.imgur.com/RYgjEJq.png
瑞鶴：http://i.imgur.com/Li9WtpP.png
大鳳：http://i.imgur.com/FTSkElo.png

7)T5日本戰列，艦R的
臻名：http://i.imgur.com/VhAfwXF.png
金剛-夏日大作戰：http://i.imgur.com/JDQ9NXf.png

8)T4金幣日巡夕張。鋼鐵少女的夕張被劃到了戰艦少女分類下
然後戰艦少女夕張-午後時光：http://i.imgur.com/xWuuHKR.png

9)T3金幣日巡，戰艦少女香取：http://i.imgur.com/pT4B71u.png

最後就是...我今晚試了四五次，點了下載之後下載不了啊QvQ
提交中轉圈了幾次之後就沒下文了

**Comment by jason199506** [comment]
順便我試做了一下，一個是從504縮小成126，另一個是378縮成126，你覺得這樣可以嗎？
(審核下，感覺沒問題直接加進去？)

https://drive.google.com/open?id=0B78jaE0utWL1QVBnOTh2dFdNSkE
https://drive.google.com/open?id=0B78jaE0utWL1RXdVNnF6dUU3Sms

**Comment by harukaxxxx** [comment]
感謝回報許多BUG
很抱歉剛收到回報的時候我就COPY到電腦所以沒有發現你有做了(跪下
另外關於回報BUG中第4點和第5點有些疑問

第4點意思是T3路易斯和我放的路易斯應該是不同的(?
但同名同級原則路易斯還能接受
但是海蓮娜就毫不相干
因此建議先把海蓮娜下架比較妥當的意思嗎?

第5點
我看了艦R百科的拉菲是寫"艾倫·薩姆納級"
確實用DD-724去找WIKI是能確定是Benson級的拉菲
這兩邊有什麼差異性呢?

最後
無法下載的問題我也搞不太清楚
嘗試了一天但是還沒什麼結果
繼續debugggggggggg QAQ

**Comment by jason199506** [comment]
4）是的，海倫娜跟布魯克林跟1905年裝甲巡洋艦聖路易斯都沒什麼關聯

5）艦R出過兩條拉菲，benson 跟 allen m somner都有出

**Comment by harukaxxxx** [comment]
了解！
兩點問題將在下次更新更正！
再次感謝多項回報！！(跪
